# Generated by Django 6.0.6 on 2026-06-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField()),
                ('loaded_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empty_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wards.ward')),
            ],
        ),
    ]
